/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.ktor.demo

import io.ktor.application.*
import io.ktor.features.*
import io.ktor.http.*
import io.ktor.response.*
import io.ktor.routing.*
import io.ktor.server.engine.*
import io.ktor.server.netty.*

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun Application.module() {
    install(DefaultHeaders)
    install(ContentNegotiation) {
        jackson {
        }
    }
    install(Routing) {
        get("/") {
            call.respondText("Hello World")
        }
        get("/health") {
            call.respond(mapOf("OK" to true))
        }
    }
}

fun main(args: Array<String>) {
    embeddedServer(Netty, 8080, watchPaths = listOf("AppKt"), module = Application::module).start()
}

